video_path: "~./Dashcam_detect_ht/Data"                                 #Location of the input data.
output_folder: "~./Dashcam_detect_ht/output"                            #Location you want to save the output results
frame_interval: 1                                                       #Number of frames per second to process and save. It is used if you are using video input
camera_intrinsics:                                                      #Provide the camera intrinsics if you plan to use a different image data source
  fx: 419.6
  fy: 419.9
  cx: 337.2
  cy: 262.6
depth_model: "LiheYoung/depth-anything-large-hf"
yolo_model: "~./Dashcam_detect_ht/Model/best.pt"                         #Trained object detection yolov8 model
sam_model: "sam_b.pt"                                                    #The weight file will be auto-downloaded in the current working directory
scale_ratio: 1204.0                                                      #this will differ according to the image size.
height_threshold: 70                                                     #The threshold is the distance of the camera to the object where it can provide correct results.
